language: python
python:
    - "3.6"

# Install dependencies
install:
    - pip install -r requirements.txt

Run tests
script:
    - pytest api/tests/v2
    - coverage run --source=api.v2 -m pytest api/tests/v2 && coverage report

after_success:
    - coveralls
