env:
  global:
    - CC_TEST_REPORTER_ID=467f19f581bc9892c4ca845ed27aa604cf0c2a6a0405ac77e3055668cc9e9be6

language: python
python:
    - "3.6"

# Install dependencies
install:
    - pip install -r requirements.txt

# Run tests
script:
    - pytest
    - coverage run --source=api -m pytest && coverage report

after_success:
    - coveralls
